# Generated by Django 5.2.7 on 2025-10-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_initial'),
        ('lineage', '0005_agent_surveillance_images'),
        ('loom', '0001_initial'),
        ('scales', '0004_remove_faction_member_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='assets',
            field=models.TextField(blank=True, help_text='Placeholder for assets from The Vault.'),
        ),
        migrations.AddField(
            model_name='operation',
            name='collateral_risk',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='operation',
            name='contingencies',
            field=models.ManyToManyField(blank=True, related_name='operations', to='codex.codexentry'),
        ),
        migrations.AddField(
            model_name='operation',
            name='personnel',
            field=models.ManyToManyField(blank=True, related_name='operations', to='lineage.agent'),
        ),
        migrations.AddField(
            model_name='operation',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='operations', to='scales.faction'),
        ),
    ]
