# Generated by Django 5.2.7 on 2025-10-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0005_agent_surveillance_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
