# Generated by Django 5.2.7 on 2025-10-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('real_name', models.CharField(help_text='CLASSIFIED', max_length=255)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('loyalty_type', models.CharField(max_length=50)),
                ('key_skill', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
