# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0001_initial'),
    ]

    operations = [
        # The RunPython operation has been moved to 0004_seed_agents.py
    ]
