# Generated by Django 5.2.7 on 2025-10-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='agent',
            name='locations',
            field=models.TextField(blank=True, help_text='Known or last seen locations.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='personality',
            field=models.TextField(blank=True, help_text='Psychological evaluation notes.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='picture_url',
            field=models.URLField(blank=True, help_text="URL to the agent's profile picture.", max_length=500),
        ),
        migrations.AddField(
            model_name='agent',
            name='summary',
            field=models.TextField(blank=True, help_text="A brief summary of the agent's history and capabilities."),
        ),
        migrations.AddField(
            model_name='agent',
            name='vehicles',
            field=models.TextField(blank=True, help_text='Known associated vehicles.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='alias',
            field=models.CharField(help_text="The agent's operational codename.", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='key_skill',
            field=models.CharField(blank=True, help_text='Primary skills or specialties.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='loyalty_type',
            field=models.CharField(blank=True, help_text='Assessed loyalty classification.', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='real_name',
            field=models.CharField(blank=True, help_text="The agent's classified real name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MIA', 'Missing in Action'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=10),
        ),
    ]
