# Generated by Django 5.2.7 on 2025-10-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0002_auto_20251027_2201'),
        ('lineage', '0002_auto_20251027_2210'),
    ]

    operations = [
    ]
