# Generated by Django 5.2.7 on 2025-10-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0002_remove_agent_created_at_remove_agent_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='alias',
            field=models.CharField(blank=True, help_text="The agent's operational codename.", max_length=100, unique=True),
        ),
    ]
