# Generated by Django 5.2.7 on 2025-10-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0003_alter_agent_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='alias',
            field=models.CharField(blank=True, help_text="The agent's operational codename.", max_length=100, null=True, unique=True),
        ),
    ]
