# Generated by Django 5.2.7 on 2025-10-27 20:05
import json
import os

from django.db import migrations

DATA_FILENAME = os.path.join(os.path.dirname(__file__), 'seed_data/0004_agents.json')


def seed_detailed_agents(apps, schema_editor):
    """Seeds the database with agents from a JSON file."""
    Agent = apps.get_model('lineage', 'Agent')
    
    with open(DATA_FILENAME) as f:
        agent_data = json.load(f)
    
    agents_to_create = [Agent(**data) for data in agent_data]
    Agent.objects.bulk_create(agents_to_create)

def unseed_detailed_agents(apps, schema_editor):
    """Removes the agents created in this migration."""
    Agent = apps.get_model('lineage', 'Agent')

    with open(DATA_FILENAME) as f:
        agent_data = json.load(f)

    aliases_to_delete = [data['alias'] for data in agent_data]
    Agent.objects.filter(alias__in=aliases_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0003_merge_20251027_2215'),
    ]

    operations = [
        migrations.RunPython(seed_detailed_agents, reverse_code=unseed_detailed_agents),
    ]
