# Generated by Django 5.2.7 on 2025-10-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0004_alter_agent_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='surveillance_images',
            field=models.TextField(blank=True, help_text='Comma-separated URLs of surveillance images.'),
        ),
    ]
