# Generated by Django 5.2.7 on 2025-10-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_site_panic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panicalert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitestate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PROTECTOR', 'Protector'), ('HEIR', 'Heir'), ('OVERLOOKER', 'Overlooker'), ('HQ', 'Headquarters')], default='OVERLOOKER', max_length=20),
        ),
    ]
