# Generated by Django 5.2.7 on 2025-10-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PROTECTOR', 'Protector'), ('HEIR', 'Heir'), ('OBSERVER', 'Observer'), ('HQ', 'Headquarters')], default='OBSERVER', max_length=20),
        ),
    ]
