# Generated by Django 5.2.7 on 2025-10-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heirslog', '0002_heirslogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heirslogentry',
            name='critical_intelligence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='heirslogentry',
            name='operational_status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='heirslogentry',
            name='proposed_actions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='heirslogentry',
            name='situational_overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='heirslogentry',
            name='strategic_analysis',
            field=models.TextField(blank=True),
        ),
    ]
