# Generated by Django 5.2.7 on 2025-10-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heirslog', '0004_alter_heirslogentry_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='heirslogentry',
            name='notes_font_family',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='heirslogentry',
            name='notes_font_size',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
