# Generated by Django 5.2.7 on 2025-10-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heirslog', '0005_heirslogentry_notes_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heirslogentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
