# Generated by Django 5.2.7 on 2025-10-28 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('threat_index', models.PositiveIntegerField(default=50, help_text='A score from 0-100')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('allies', models.CharField(blank=True, help_text='Comma-separated list of allied factions', max_length=255)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Details of the compromising information.')),
                ('potency', models.CharField(default='High', max_length=50)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leverage_points', to='scales.faction')),
            ],
        ),
    ]
