# Generated by Django 5.2.7 on 2025-10-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="The agent's real name, if known.", max_length=255)),
                ('alias', models.CharField(blank=True, max_length=100, unique=True)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('known_locations', models.TextField(blank=True)),
                ('known_vehicles', models.TextField(blank=True)),
                ('threat_level', models.PositiveIntegerField(blank=True, default=50, help_text='A score from 0-100 indicating threat level.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='faction',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='factions', to='scales.agent'),
        ),
    ]
