# Generated by agent: add Connection model linking Scales.Agent to Lineage.Agent
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0005_agent_deleted_at_faction_deleted_at_and_more'),
        ('lineage', '0005_agent_surveillance_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('INFORMANT', 'Informant'), ('LEVERAGE', 'Leverage (Blackmail)'), ('FAMILY_TIE', 'Family Tie'), ('PAST_AFFILIATION', 'Past Affiliation'), ('RIVAL', 'Rival'), ('HANDLER', 'Handler')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lineage_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_connections', to='lineage.agent')),
                ('scales_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='scales.agent')),
            ],
            options={
                'unique_together': {('scales_agent', 'lineage_agent')},
            },
        ),
    ]
