# Generated by Django 5.2.7 on 2025-10-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0007_factionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factionhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
