# Generated by agent: extend Echo for The Silo and add SiloComment
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_echo_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='echo',
            name='confidence',
            field=models.CharField(choices=[('DIRECT', 'Direct Observation'), ('VERIFIED', 'Verified Informant'), ('CORROBORATED', 'Corroborated Rumor'), ('UNVERIFIED', 'Unverified Tip')], default='UNVERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='echo',
            name='evidence_urls',
            field=models.TextField(blank=True, help_text='Comma-separated list of URLs for evidence'),
        ),
        migrations.AddField(
            model_name='echo',
            name='involved_entities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='echo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'New'), ('UNDER_REVIEW', 'Under Review'), ('ACTIONED', 'Actioned'), ('DISMISSED', 'Dismissed'), ('PROMOTED', 'Promoted')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SiloComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('echo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='codex.echo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['created_at']},
        ),
    ]

