# Generated by agent: add assigned_agents M2M on Echo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0004_silo_extensions'),
        ('lineage', '0005_agent_surveillance_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='echo',
            name='assigned_agents',
            field=models.ManyToManyField(blank=True, related_name='assigned_reports', to='lineage.agent'),
        ),
    ]

