# Generated by agent: extend Task status choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0005_echo_assigned_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='OPEN', max_length=12),
        ),
    ]

