# Generated by Django 5.2.7 on 2025-10-29 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0008_alter_vaultitem_id'),
        ('lineage', '0006_agent_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('photos_urls', models.TextField(blank=True, help_text='Comma-separated list of photo URLs')),
                ('blueprints_urls', models.TextField(blank=True, help_text='Comma-separated blueprint URLs')),
                ('security_details', models.TextField(blank=True)),
                ('vulnerabilities', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stored_items', models.ManyToManyField(blank=True, related_name='properties', to='codex.vaultitem')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=100)),
                ('license_plate_clean', models.CharField(blank=True, max_length=50)),
                ('license_plate_cloned', models.CharField(blank=True, max_length=50)),
                ('modifications', models.TextField(blank=True, help_text='Armor, compartments, etc.')),
                ('last_known_location', models.CharField(blank=True, max_length=255)),
                ('picture_urls', models.TextField(blank=True, help_text='Comma-separated URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='lineage.agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
