# Generated by Django 5.2.7 on 2025-10-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0010_bulletin_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bulletinack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
