# Generated by Django 5.2.7 on 2025-10-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0013_codex_category_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codexcategoryconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
