# Generated by Django 5.2.7 on 2025-10-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0014_alter_codexcategoryconfig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('SILO_REPORT', 'New Silo Report'), ('TASK_ASSIGNED', 'Task Assigned'), ('OPERATION_STATUS', 'Operation Status Changed'), ('MANTLE', "Protector's Mantle"), ('BULLETIN_ACK', 'Bulletin Acknowledged')], max_length=40),
        ),
    ]
