# Generated by Django 5.2.7 on 2025-10-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexprofile',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
