# Generated by Django 5.2.7 on 2025-10-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scales', '0009_agent_surveillance_images_faction_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('aliases', models.TextField(blank=True)),
                ('classification', models.CharField(blank=True, choices=[('ASSET_TALON', 'Asset (Talon)'), ('CRIMINAL_AFFILIATED', 'Criminal (Affiliated)'), ('CRIMINAL_UNAFFILIATED', 'Criminal (Unaffiliated)'), ('LAW_ENFORCEMENT', 'Law Enforcement'), ('GOVERNMENT_DOJ', 'Government / DOJ'), ('CIVILIAN_HIGH', 'Civilian (High Value)'), ('CIVILIAN_LOW', 'Civilian (Low Value)')], max_length=32, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('DECEASED', 'Deceased'), ('INCARCERATED', 'Incarcerated'), ('MISSING', 'Missing')], default='ACTIVE', max_length=16, null=True)),
                ('threat_level', models.CharField(blank=True, choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NONE', max_length=16, null=True)),
                ('biography', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('known_locations', models.TextField(blank=True)),
                ('known_vehicles', models.TextField(blank=True)),
                ('surveillance_urls', models.TextField(blank=True, help_text='Comma-separated URLs of surveillance media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliations', models.ManyToManyField(blank=True, related_name='index_profiles', to='scales.faction')),
            ],
        ),
    ]
