# Generated by Django 5.2.7 on 2025-10-29 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MantleDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('heir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mantle_delegation', to=settings.AUTH_USER_MODEL)),
                ('protector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_mantle_delegations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
