# Generated by Django 5.2.7 on 2025-10-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0002_agent_faction_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
