# Generated by Django 5.2.7 on 2025-10-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0003_agent_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='member_count',
        ),
    ]
