# Generated by Django 5.2.7 on 2025-10-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0004_remove_faction_member_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='faction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='leverage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
