# Generated by Django 5.2.7 on 2025-10-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0008_alter_factionhistory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='surveillance_images',
            field=models.TextField(blank=True, help_text='Comma-separated URLs of surveillance images.'),
        ),
        migrations.AddField(
            model_name='faction',
            name='picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
