# Generated by agent: add started_at and ended_at to Operation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loom', '0003_operation_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

